/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { whiteMaterial } from "../constants/materials";

export function Keyboard() {
  const { nodes } = useGLTF("./models/keyboard.gltf");

  return (
    <group dispose={null}>
      <group scale={0.003} position={[0, -0.85, 3.5]}>
        <group position={[27.269, 17.597, 154.594]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["keyboard-base"].geometry}
            material={whiteMaterial}
            position={[-0.963, -35.774, -155.103]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2.geometry}
              material={whiteMaterial}
              position={[-4.648, -3.898, -0.906]}
            />
          </mesh>
          <group position={[426.612, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_1"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[304.823, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_2"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[183.034, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_3"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[61.205, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_4"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-60.923, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_5"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-183.034, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_6"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-304.823, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_7"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-426.612, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_8"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[183.034, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_9"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[61.205, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_10"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-60.923, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_11"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-183.034, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_12"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-304.823, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_13"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-426.612, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_14"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-548.4, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_15"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[548.4, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_16"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[426.612, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_17"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[304.823, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_18"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[183.034, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_19"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[61.245, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_20"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-60.923, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_21"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-183.034, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_22"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-304.823, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_23"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-426.612, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_24"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[426.612, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_25"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[670.189, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_26"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[548.4, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_27"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[304.823, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_28"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-60.923, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_29"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-548.4, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_30"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-670.189, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_31"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[670.189, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_32"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-670.189, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_33"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-670.189, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_34"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[670.189, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_35"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[670.189, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_36"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[548.4, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_37"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[548.4, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_38"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[426.612, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_39"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[304.823, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_40"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[670.189, 0, -32.715]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_41"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[183.034, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_42"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-183.034, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_43"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-304.823, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_44"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-426.612, 0, 89.074]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_45"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-670.189, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_46"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-670.189, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_47"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-548.4, 0, -275.853]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_48"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-548.4, 0, -155.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-548.4, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-426.612, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-304.823, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-183.034, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[-60.923, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[61.245, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[183.034, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[304.823, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[426.612, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
          <group position={[548.4, 0, -398.344]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["key-base_49"].geometry}
              material={whiteMaterial}
              position={[-0.934, -1.985, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
